// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxdy_8Ui8DByPPKArnpj4dla6YMzsFi0',
    appId: '1:805124804072:web:e28278e89b10d33263a85d',
    messagingSenderId: '805124804072',
    projectId: 'indagram-sumampong-sanch-b1799',
    authDomain: 'indagram-sumampong-sanch-b1799.firebaseapp.com',
    storageBucket: 'indagram-sumampong-sanch-b1799.appspot.com',
    measurementId: 'G-81XY06MTTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfJ5ieDas8uUfKcEI17IMLju31wNZtgM',
    appId: '1:805124804072:android:2eed56ba01f188c963a85d',
    messagingSenderId: '805124804072',
    projectId: 'indagram-sumampong-sanch-b1799',
    storageBucket: 'indagram-sumampong-sanch-b1799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGuc2N4ZZuWRyqRyu6uUhIYVWFwbq0zE',
    appId: '1:805124804072:ios:d8d54205138fcf8a63a85d',
    messagingSenderId: '805124804072',
    projectId: 'indagram-sumampong-sanch-b1799',
    storageBucket: 'indagram-sumampong-sanch-b1799.appspot.com',
    iosClientId: '805124804072-piinf9ji9i95bmvs5r5rf7ai3lr0nd5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagramMidterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGuc2N4ZZuWRyqRyu6uUhIYVWFwbq0zE',
    appId: '1:805124804072:ios:cb750f9f02b8872b63a85d',
    messagingSenderId: '805124804072',
    projectId: 'indagram-sumampong-sanch-b1799',
    storageBucket: 'indagram-sumampong-sanch-b1799.appspot.com',
    iosClientId: '805124804072-rk09cmni0jt1urub014bsjvts9u3d9ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.indagramMidterm.RunnerTests',
  );
}
